version: '2'
services:
  web:
    image: helder/nginx
    ports:
      - 80
    volumes_from:
      - uwsgi
    environment:
      - CONF_APP=django
      - CONF_UPSTREAM=uwsgi:9000

  uwsgi:
    build: .
    depends_on:
      - db
      - mail
    volumes:
      - ./:/usr/src/app
      - prod:/usr/local/lib/python2.7/site-packages
    working_dir: /usr/src/app/src
    environment:
      - DJANGO_SETTINGS_MODULE=confs.settings.prod

  manage:
    build: .
    entrypoint:
      - python
      - manage.py
    command: runserver 0.0.0.0:80
    ports:
      - 80
    links:
      - db
      - mail
    volumes:
      - ./:/usr/src/app
      - dev:/usr/local/lib/python2.7/site-packages
    working_dir: /usr/src/app/src
    environment:
      - DJANGO_SETTINGS_MODULE=confs.settings.dev
    env_file:
      - .env

  db:
    image: helder/mysql
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=twitter_clone
      - MYSQL_ROOT_PASSWORD=root

  node:
    image: helder/node
    command: gosu node /bin/true
    volumes:
      - ./:/data

  mail:
    image: helder/mailcatcher
    ports:
      - 80

volumes:
  dev:
    driver: local
  prod:
    driver: local
